# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 605709c9180f403e2f620d44c79e5d6df9c4fddd1373bf6763bcb4134827d06732e52eb5a9ed4df707b711b69830613df3cbb21c3fb7d2ac4e95fc6cae07c7b4

test:
  secret_key_base: bab12eaedb214368d1efb37420e58a63de43eda353872edbeb23c21ca8e1430dbfa0c4aef3c0eb0fc804428823d509587ad0a3654eb6082b452390e974344b43

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
